### PR TITLE
Use concrete field type for type stability

### PR DESCRIPTION
**Pull request by yha**
Makes everything inferrable and faster.

### CODE REVIEW

**Comment by yha** [comment]
Tests seem to fail here, although they pass locally on my machine. I think the difference is in `OffsetArrays` version. I'll look into it.

**Comment by yha** [comment]
The problem is that JuliaArrays/OffsetArrays.jl#90 added a custom axis type to the `OffsetAxis` union, so the ambiguities resolved in #1 crop up again. This breaks existing functionality from #1 (nothing to do with this PR).
I think now the proper solution would involve fixing the way offset arrays are designed in Base, since the current design seems to basically guarantee that different packages defining `similar` methods will trigger ambiguities when used together.
For now I suppose we can either add a dependency on `OffsetArrays` and disambiguate on `OffsetArrays.OffsetAxis`, or add a version constraint for `OffsetArrays` (but can a version constraint be used without a dependency?).

**Comment by Vexatos** [comment]
I really wish there was a way to pull `IdOffsetRange` without having to add a hard dependency on OffsetArrays, at least for now. That is just really ugly and wasteful.

**Comment by Vexatos** [comment]
This PR looks good unrelated to the OffsetArrays issue, which I actually made an issue for now. Thanks for your contribution, and for looking into this.

**Pull request merged**
