### PR TITLE
Support more array mutation methods

### LINKED ISSUE #21: Missing push! implementation
```julia
julia> using CircularArrays

julia> c = CircularVector([1,2,3])
3-element CircularVector(::Vector{Int64}):
 1
 2
 3

julia> push!(c, 4)
ERROR: MethodError: no method matching resize!(::CircularVector{Int64, Vector{Int64}}, ::Int64)

Closest candidates are:
  resize!(::Vector, ::Integer)
   @ Base array.jl:1246
  resize!(::BitVector, ::Integer)
   @ Base bitarray.jl:814
  resize!(::SparseArrays.ReadOnly, ::Any)
   @ SparseArrays ~/.julia/juliaup/julia-1.9.3+0.x64.linux.gnu/share/julia/stdlib/v1.9/SparseArrays/src/readonly.jl:33
  ...

Stacktrace:
 [1] _append!(a::CircularVector{Int64, Vector{Int64}}, #unused#::Base.HasLength, iter::Tuple{Int64})
   @ Base ./array.jl:1134
 [2] append!(a::CircularVector{Int64, Vector{Int64}}, iter::Tuple{Int64})
   @ Base ./array.jl:1126
 [3] push!(a::CircularVector{Int64, Vector{Int64}}, iter::Int64)
   @ Base ./array.jl:1127
 [4] top-level scope
   @ REPL[6]:1
```

### PR DESCRIPTION
**Pull request by terasakisatoshi**
This PR closes #21

@juliohm, @Vexatos

### CODE REVIEW

**Comment by terasakisatoshi** [comment]
Should we still support 1.3?

**Comment by terasakisatoshi** [comment]
Can I add `Base.sizehint!(a::CircularVector, sz::Integer) = (sizehint!(parent(a), sz); a)` method to pass CI for Julia nightly?

**Comment by terasakisatoshi** [comment]
Oops...

```julia
 Got exception outside of a @test
  StackOverflowError:
  Stacktrace:
        [1] sizehint!(a::Vector{Int64}, sz::Int64; first::Bool, shrink::Bool)
          @ Base ./array.jl:1478
        [2] sizehint!
          @ ./array.jl:1478 [inlined]
        [3] sizehint!
          @ ~/work/CircularArrays.jl/CircularArrays.jl/src/CircularArrays.jl:136 [inlined]
        [4] sizehint!
          @ ./array.jl:1517 [inlined]
        [5] _append!
          @ ./array.jl:1317 [inlined]
        [6] append!
          @ ./array.jl:1309 [inlined]
        [7] push!(a::CircularVector{Int64, Vector{Int64}}, iter::Int64)
          @ Base ./array.jl:1310
        [8] _append!
          @ ./array.jl:1319 [inlined]
  --- the above 3 lines are repeated 79981 more times ---
   [239952] append!
          @ ./array.jl:1309 [inlined]
append!: Error During Test at /home/runner/work/CircularArrays.jl/CircularArrays.jl/test/runtests.jl:127
  Got exception outside of a @test
  StackOverflowError:
```

**Comment by juliohm** [comment]
@Vexatos can you please review this PR? It fixes the issue on recent Julia versions.

**Comment by Vexatos** [comment]
The tests not passing for nightly and 1.3 would definitely have to be fixed before I review this. I also dislike the idea of dropping support for Julia 1.3 over this.

**Comment by terasakisatoshi** [comment]
> I also dislike the idea of dropping support for Julia 1.3 over this.

Could you explain why you want to pass CI for Julia v1.3?  [v1.6 is now LTS](https://discourse.julialang.org/t/julia-v1-7-0-has-been-released-and-v1-6-is-now-lts/72336) and v1.3 is obsolete.

**Comment by juliohm** [comment]
bump @Vexatos

**Comment by Vexatos** [comment]
You make a good point. Since the next release will be a minor version up anyway, I can probably drop support for 1.3, a version which I was still using myself until a while ago. The large number of tests is greatly appreciated; I'll merge this once you add a test for `sizehint!` so that test coverage remains complete.

**Comment by Vexatos** [comment]
I added the relevant test myself. It looks like the tests fail on Julia 1.6 right now, because the `@test_throws` do not produce the expected outcome as the syntax changed slightly.

**Comment by Vexatos** [comment]
Looks like nightly tests are hitting an infinite loop involving `push!`. Perhaps this means that `push!` will have to be implemented manually.

**Pull request merged**
